### ISSUE TITLE
OSTree-based rootfs

### ISSUE THREAD

**Issue by halverneus** [dbnicholson/deb-ostree-builder#4]
I'm using this project as a guide, and I don't know anyone else to ask these questions. I'm trying to create a OSTree, bootable image on an Nvidia Jetson (arm64). Some of the requirements are Nvidia-limited (or I would just use something like Yocto). Besides the extraction of Jetson_Linux...tbz2 and the './apply_binaries.sh' and immediately following lines, nothing is Nvidia-specific... I just create an image based on ARM64 Ubuntu Bionic (Nvidia requirement), install some dependencies and attempt to make the filesystem OSTree-bootable. Once I flash the device, I've executed:

```bash
ostree admin init-fs /sysroot
ostree admin os-init mine
ostree admin set-origin http://10.0.1.4:8080 mine
```

The first two commands run fine (I can't get them to run in the chroot; only on the device), but the third gives me "error: Not currently booted into an OSTree system". OSTree is a topic that I can't find much information on other than the documentation that has a single reference page. I've been using this repository as reference, but I don't know the values of the environment variables used in the scripts nor where to find them (nor sane choices for values). Any chance you might be able to tell what I'm missing in the script below for creating a minimal OSTree image? I'm hoping to open source and write-up what I've learned for others interested in making OSTree-based devices, once I've successfully flashed a device and updated the file system.

```bash
#!/bin/bash

set -euo pipefail # Exits script on any error.

# To run this script a few base packages are required. Run the following command
# to install this base packages:
#
# apt install -y build-essential debootstrap qemu-user-static
#

HOMEDIR="/home/$USER"
echo "Will be using SSH key from the following home directory: $HOMEDIR"

# Start fresh and remove any existing installs.
sudo rm -rf out || /bin/true
mkdir out
cd out

# Extract the Jetson tools
tar -xf ../Jetson_Linux_R32.4.4_aarch64.tbz2
cd Linux_for_Tegra

# Build the filesystem.
sudo qemu-debootstrap --arch=arm64 bionic rootfs

sudo /bin/bash -c "echo \"deb http://ports.ubuntu.com/ubuntu-ports bionic main universe\" > rootfs/etc/apt/sources.list"

sudo chroot rootfs /bin/bash -c "apt update && apt install -y libdrm-common libdrm2 libegl-mesa0 libegl1 libgbm1 libglapi-mesa libglvnd0 libwayland-client0 libwayland-server0 libx11-xcb1 libxau6 libxcb-dri2-0 libxcb-dri3-0 libxcb-present0 libxcb-sync1 libxcb-xfixes0 libxcb1 libxdmcp6 libxshmfence1 multiarch-support device-tree-compiler fontconfig fontconfig-config fonts-dejavu-core libcairo2 libdatrie1 libevdev2 libfontconfig1 libfreetype6 libgles2 libgraphite2-3 libgudev-1.0-0 libharfbuzz0b libinput-bin libinput10 libjpeg-turbo8 libmtdev1 libpango-1.0-0 libpangoft2-1.0-0 libpixman-1-0 libpng16-16 libpython-stdlib libpython2.7-minimal libpython2.7-stdlib libthai-data libthai0 libunwind8 libwacom-bin libwacom-common libwacom2 libwayland-cursor0 libwayland-egl1-mesa libx11-6 libx11-data libxcb-render0 libxcb-shm0 libxext6 libxkbcommon0 libxrender1 python python-minimal python2.7 python2.7-minimal gstreamer1.0-plugins-base iso-codes libasound2-data libcdparanoia0 libogg0 libopus0 liborc-0.4-0 libtheora0 libvisual-0.4-0 libvorbis0a libvorbisenc2 libgstreamer-plugins-bad1.0-0 libasound2 libpangocairo-1.0-0 openssh-server network-manager ostree && rm -rf /var/lib/apt/lists/*"

sudo mkdir -p rootfs/root/.ssh && sudo cp $HOMEDIR/.ssh/id_rsa.pub rootfs/root/.ssh/authorized_keys

sudo ./apply_binaries.sh
sudo rm -f rootfs/lib/systemd/system/nv-oem-config*.*
sudo rm -f rootfs/usr/sbin/nv-oem-config-firstboot
sudo rm -f rootfs/etc/systemd/nv-oem-config*.sh
sudo rm -f rootfs/etc/nv-oem-config.conf.*
sudo rm rootfs/README.txt

# Adapt filesystem to OSTree
# - /bin -> /usr/bin
sudo mv rootfs/bin/* rootfs/usr/bin/ && sudo rmdir rootfs/bin && sudo ln -s /usr/bin rootfs/bin
# - /sbin -> /usr/sbin
sudo mv rootfs/sbin/* rootfs/usr/sbin/ && sudo rmdir rootfs/sbin && sudo ln -s /usr/sbin rootfs/sbin
# - /home -> /var/home
sudo mkdir rootfs/var/home && sudo rmdir rootfs/home && sudo ln -s /var/home rootfs/home
# - /lib -> /usr/lib
sudo mv rootfs/lib/aarch64-linux-gnu/* rootfs/usr/lib/aarch64-linux-gnu/ && sudo rmdir rootfs/lib/aarch64-linux-gnu
sudo mv rootfs/lib/systemd/* rootfs/usr/lib/systemd/ && sudo rmdir rootfs/lib/systemd
sudo mv rootfs/lib/* rootfs/usr/lib/ && sudo rmdir rootfs/lib && sudo ln -s /usr/lib rootfs/lib
# - /opt -> /var/opt
sudo mv rootfs/opt/* rootfs/var/opt/ && sudo rmdir rootfs/opt && sudo ln -s /var/opt rootfs/opt
# - /root -> /var/roothome
sudo mv rootfs/root rootfs/var/roothome && sudo ln -s /var/roothome rootfs/root
# - /media -> /run/media
sudo rmdir rootfs/media && sudo ln -s /run/media rootfs/media
# - /etc -> /usr/etc
# sudo mv rootfs/etc rootfs/usr/etc && sudo mkdir rootfs/etc

# Setup OSTree
sudo mkdir rootfs/sysroot
sudo ln -s /sysroot/ostree rootfs/ostree

# Setup OSTree-Systemd tmpfiles.
sudo bash -c 'cat <<EOF > rootfs/usr/lib/tmpfiles.d/ostree.conf
L /var/home - - - - ../sysroot/home
d /var/roothome 0700 root root -
d /var/opt 0755 root root -
d /var/local 0755 root root -
d /run/media 0755 root root -
EOF'

echo "To flash device run: sudo ./flash.sh jetson-agx-xavier-devkit mmcblk0p1"

```

**Comment by halverneus** [comment]
If it helps, I can run the following on the device:

```bash
ostree admin init-fs /sysroot
ostree admin os-init mine
ostree remote add mine http://10.0.1.4:8080 --no-gpg-verify
ostree pull mine mine
ostree refs --repo=/sysroot/ostree/repo
ostree admin deploy mine:mine --sysroot=/sysroot --os=mine
```

However the last command  gives me "error: Failed to find kernel in /usr/lib/modules, /usr/lib/ostree-boot or /boot". I have a "/usr/lib/modules/4.9.140-tegra" directory and "/boot/extlinux/extlinux.conf" if that helps give an idea of how the system is built. I feel like I'm nearly there... but I don't actually know.

**Comment by dbnicholson** [comment]
It's a bit confusing because the ostree commit you're deploying and the system you're deploying the commit to are separate things. The script you've pasted above is about creating a commit. You want to take your `rootfs` directory and commit it. See the end of https://github.com/dbnicholson/deb-ostree-builder/blob/simple-builder/deb-ostree-builder.

Once you have that in a persistent repository, that's when you create the system that will run the commit. Typically you would run this from outside of the actual device you're flashing rather than chrooting into it because the ostree managed filesystem is constructed at runtime. See https://github.com/dbnicholson/deb-ostree-builder/blob/simple-builder/create-deployment.

For your particular question, `admin set-origin` is intended to be executed from a running ostree system to change the URL of the deployment's origin server. Instead what you want to do is add a remote target system's repo, pull your built commit and then deploy it. One note is that this does require that you have ostree installed on the host, which might be the reason you were trying to do it from the chroot. You could also chroot into your commit's debootstrapped environment with ostree and do the operations there after bind mounting various things into it.

Anyways, the basic steps assuming `rootfs` is the commit working directory, `repo` is the repository to make the commit and `device` is a directory where you'll build the contents to actually flash to the device:

* `debootstrap` etc in `rootfs` as in your script above.
* `ostree --repo=repo commit -b someref rootfs`
* `ostree admin init-fs device`
* `ostree --sysroot=device admin os-init mine`
* `ostree --repo=device/ostree/repo remote add mine http://url/to/repo`
* `ostree --repo=device/ostree/repo pull-local --remote=mine repo someref`
* `ostree --sysroot=device admin deploy --os=mine mine:someref`

At this point `device` is basically prepared to flash to a filesystem on a real device. There are some details about booting that I left out, but those are the basics.

**Comment by halverneus** [comment]
I'll give that a try. That appears to be the hurdle I couldn't quite jump (everything I can find online tells me how to build images, commit images, deploy images, etc..., but I have been trying to create the initial image to flash to a device, which I couldn't find anything). This should be helpful; thank you! I'll give you an update, either way it goes.

**Comment by halverneus** [comment]
Ran those steps and everything went great until the last step where I got: 

```bash
$ ostree --sysroot=rootfs admin deploy --os=mine mine:mine
error: Failed to find kernel in /usr/lib/modules, /usr/lib/ostree-boot or /boot
```

Same issue I was having when attempting to make the changes on-device. I don't suppose you have any ideas off the top of your head how to help it find the kernel and move forward? So close... Thank you, again!

**Comment by dbnicholson** [comment]
First you have to install an actual kernel if you intend to boot the device and I didn't see one in your script, although I may have missed it. On debian that would typically be something like installing `linux-image-amd64`, but maybe you have something different to support your nvidia board.

Anyways, ostree looks for the kernel and initramfs to be named a specific way so that it can deal with them as immutable files in the same manner that it does the checksummed objects in the commit. Here's the part of our script that does that:

```
# OSTree uses a single checksum of the combined kernel and initramfs
# to manage boot. Determine the checksum and rename the files the way
# OSTree expects.
echo "Renaming kernel and initramfs per OSTree requirements"
pushd "$BUILDDIR"/boot >/dev/null

vmlinuz_match=(vmlinuz*)
vmlinuz_file=${vmlinuz_match[0]}
initrd_match=(initrd.img* initramfs*)
initrd_file=${initrd_match[0]}

csum=$(cat ${vmlinuz_file} ${initrd_file} | \
	      sha256sum --binary | \
	      awk '{print $1}')
echo "OSTree boot checksum: ${csum}"

mv ${vmlinuz_file} ${vmlinuz_file}-${csum}
mv ${initrd_file} ${initrd_file/initrd.img/initramfs}-${csum}
```

The `csum` calculation is what's needed. This is actually in the ostree documentation at https://ostreedev.github.io/ostree/deployment/#contents-of-a-deployment. Booting is probably the trickiest part as it's the most platform dependent.

Also consider running `ostree --verbose`. There might be some information in there about what it's looking for.

**Comment by halverneus** [comment]
Thanks. Just to document (and to correct me if I am going down a wrong path), I have the following files that appear relevant:
```bash
/boot/Image
/boot/initrd
/boot/extlinux/extlinux.conf
```

I've taken a non-OSTree image, moved the kernel and initrd files to the new locations (locations based on EOS VM I'm using as a template) and updated /boot/extlinux/extlinux.conf and booted to verify the raw image works:

```bash
/usr/lib/modules/4.9.140-tegra/vmlinuz
/usr/lib/modules/4.9.140-tegra/initrd
```

I'm attempting to create a new OSTree commit and rebuild from that. Given what you are showing, it sounds like I just need to rename the files in /boot to:

```bash
/boot/vmlinuz-${csum}
/boot/initrd_file/initrd.img/initramfs-${csum}
```

... and update /etc/extlinux/extlinux.conf accordingly. Does that sound correct?

**Comment by halverneus** [comment]
Looks like I might also need to include tegra194-p2888-0001-p2822-0000.dtb as devicetree-${csum}. I'm assuming a "Device Tree Blob" is the requested 'devicetree'. I feel so close to having this working...

**Comment by dbnicholson** [comment]
Yeah, I think that's right. I've been guiding you down the legacy pathways because we were early adopters at Endless and haven't adapted yet.

With modern ostree, this can all be done a bit more simply by putting all 3 in `/usr/lib/modules/$kver/{vmlinuz,initramfs.img,devicetree}`. But it does look like the code supports the legacy `/boot/devicetree-${csum}` path as well. The modern way might be simpler as you don't need to worry about calculating the boot checksum, but you do need to rename the files appropriately.

**Comment by halverneus** [comment]
I've had some great luck with the advice you have given me. Unfortunately, I'm stuck with Nvidia-flashing-specific issues that don't apply here. I did run into something I wasn't expecting, though... When I tried to delete the directory containing the OSTree filesystem I was attempting to deploy (so I could remake clean), I found I couldn't delete the directory:

```bash
root@jstreetsnb:/home/jstreets/Dev/out/Linux_for_Tegra/rootfs/ostree/deploy/mine/deploy/bd3c583827cca471c3b23fb8c128e7d74cf2dd3aedf4f3b5d10a13ead29c28c1.0# ls -lah
total 56K
drwxr-xr-x 14 root root 4.0K Jan  5 12:00 .
drwxr-xr-x  3 root root 4.0K Jan  5 12:02 ..
lrwxrwxrwx  1 root root    8 Jan  5 12:00 bin -> /usr/bin
drwxr-xr-x  2 root root 4.0K Jan  5 12:02 boot
drwxr-xr-x  2 root root 4.0K Dec 31  1969 dev
drwxr-xr-x  2 root root 4.0K Jan  5 12:02 etc
lrwxrwxrwx  1 root root    9 Jan  5 12:00 home -> /var/home
lrwxrwxrwx  1 root root    8 Jan  5 12:00 lib -> /usr/lib
lrwxrwxrwx  1 root root   10 Jan  5 12:00 media -> /run/media
drwxr-xr-x  2 root root 4.0K Dec 31  1969 mnt
lrwxrwxrwx  1 root root    8 Jan  5 12:00 opt -> /var/opt
lrwxrwxrwx  1 root root   15 Jan  5 12:00 ostree -> /sysroot/ostree
drwxr-xr-x  2 root root 4.0K Dec 31  1969 proc
lrwxrwxrwx  1 root root   13 Jan  5 12:00 root -> /var/roothome
drwxr-xr-x  2 root root 4.0K Jan  5 12:02 run
lrwxrwxrwx  1 root root    9 Jan  5 12:00 sbin -> /usr/sbin
drwxr-xr-x  2 root root 4.0K Dec 31  1969 srv
drwxr-xr-x  2 root root 4.0K Dec 31  1969 sys
drwxr-xr-x  2 root root 4.0K Dec 31  1969 sysroot
drwxrwxrwt  2 root root 4.0K Dec 31  1969 tmp
drwxr-xr-x  2 root root 4.0K Jan  5 12:02 usr
drwxr-xr-x  2 root root 4.0K Jan  5 12:02 var
root@jstreetsnb:/home/jstreets/Dev/out/Linux_for_Tegra/rootfs/ostree/deploy/mine/deploy/bd3c583827cca471c3b23fb8c128e7d74cf2dd3aedf4f3b5d10a13ead29c28c1.0# rm home
rm: cannot remove 'home': Operation not permitted
root@jstreetsnb:/home/jstreets/Dev/out/Linux_for_Tegra/rootfs/ostree/deploy/mine/deploy/bd3c583827cca471c3b23fb8c128e7d74cf2dd3aedf4f3b5d10a13ead29c28c1.0# lsattr
--------------e----- ./run
--------------e----- ./usr
--------------e----- ./srv
--------------e----- ./proc
--------------e----- ./dev
lsattr: Operation not supported While reading flags on ./bin
lsattr: Operation not supported While reading flags on ./root
--------------e----- ./tmp
lsattr: Operation not supported While reading flags on ./home
--------------e----- ./boot
lsattr: Operation not supported While reading flags on ./lib
--------------e----- ./var
lsattr: Operation not supported While reading flags on ./opt
--------------e----- ./mnt
--------------e----- ./sys
--------------e----- ./sysroot
--------------e----- ./etc
lsattr: Operation not supported While reading flags on ./media
lsattr: Operation not supported While reading flags on ./sbin
lsattr: Operation not supported While reading flags on ./ostree
root@jstreetsnb:/home/jstreets/Dev/Linux_for_Tegra/rootfs/ostree/deploy/mine/deploy/bd3c583827cca471c3b23fb8c128e7d74cf2dd3aedf4f3b5d10a13ead29c28c1.0# chattr -i home
chattr: Operation not supported while reading flags on home
```

Have you had any experience with this and have any solutions?

**Comment by halverneus** [comment]
Nevermind. The immutable attribute was set on the directory... I was looking one level too deep.

**Comment by halverneus** [comment]
Thank you for all the help!
